extends Node
enum SPELL_DIALOG_MODES{SHOW, UPGRADE, ADD_SPELL}

enum RANGE_TYPE{CIRCURAL, LINE}
enum SPELL_TYPE{OFFENSIVE, HEAL, STATUS}
enum STATUS_TYPE{SHIELD, VULNERABLE}
enum INTERACTABLES{CONTAINER, UPGRADE, SPELL, HEART}
